### ISSUE TITLE
[BUG #01] 프로필 페이지에서 댓글 단 글을 눌렀을 때 invalid question id

### ISSUE THREAD

**Issue by ksiyeon27** [wafflestudio19-5/team1-server#53]
<img width="1251" alt="스크린샷 2022-01-08 오후 2 51 14" src="https://user-images.githubusercontent.com/76062959/148633312-f46f1916-a042-4e9c-9681-9985cbab0e57.png">
여기서 My nickname is amazing! 눌렀을 때

<img width="1280" alt="스크린샷 2022-01-08 오후 2 51 31" src="https://user-images.githubusercontent.com/76062959/148633314-5bbf35bb-b4a4-4396-a211-c0ba561b1f0f.png">
이런 화면이 뜹니다.

**Comment by yg-moon** [comment]
앗 그것은 아직 구현이 안 된 부분인데 설명이 미비했습니다. 추후 구현 예정입니다!
