### ISSUE TITLE
[BUG #03] 댓글 수정 시 빈 댓글 허용됨

### ISSUE THREAD

**Issue by yeonsumia** [wafflestudio19-5/team1-server#55]
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/81272473/148633539-db153337-4d60-4003-b18f-cc2ee8762893.png">

다음과 같이 빈 댓글이 허용됩니다.

**Comment by kmsgm** [comment]
이건 프론트단에서 쉽게 해결할 수 있을 것 같습니다.

**Comment by yg-moon** [comment]
해결되었습니다!
