### ISSUE TITLE
[Bug] 미리보기에 한자가 나타나지 않습니다

### ISSUE THREAD

**Issue by yabsed** [wafflestudio19-5/team1-server#57]
<img width="1440" alt="스크린샷 2022-01-08 오후 6 01 30" src="https://user-images.githubusercontent.com/14042027/148638519-4f84f688-cb7c-4e1a-973b-0bfa704f0412.png">
<img width="1439" alt="스크린샷 2022-01-08 오후 6 00 36" src="https://user-images.githubusercontent.com/14042027/148638523-c465cc49-0b30-40ee-b765-af5404d5a4ee.png">

**Comment by yg-moon** [comment]
상세한 버그 검증 감사합니다! 아마 프론트에서 사용한 마크다운 라이브러리의 제약인 것 같습니다.

**Comment by yg-moon** [comment]
지금은 잘 보입니다. 해결된 것 같네요!
